use std::io::Result;
use std::{fs, path::Path};

fn main() -> Result<()> {
    #[cfg(feature = "zmq")]
    {
        prost_build::Config::new()
            .compile_protos(&["proto/sim.proto"], &["proto"])?;
        println!("cargo:rerun-if-changed=proto/sim.proto");
    }

    let tasks_toml = Path::new("tasks.toml");
    println!("cargo:rerun-if-changed={}", tasks_toml.display());

    let content = fs::read_to_string(tasks_toml)?;
    let config: ToolConfig = toml::from_str(&content)
        .expect("failed to parse tasks.toml");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("tool_defs.rs");
    let mut code = String::from(
        "// Generated by build.rs from tasks.toml — do not edit.\n\
         pub const TOOL_DEFS: &[ToolDef] = &[\n",
    );

    for tool in &config.tool {
        let addr = |v: &Option<String>| match v {
            Some(s) => format!("Some(\"{s}\")"),
            None => "None".to_string(),
        };
        code.push_str(&format!(
            "    ToolDef {{\n\
             \x20       name: \"{}\",\n\
             \x20       hint: \"{}\",\n\
             \x20       tcp_addr: {},\n\
             \x20       zmq_sub_addr: {},\n\
             \x20       zmq_pub_addr: {},\n\
             \x20   }},\n",
            tool.name, tool.hint,
            addr(&tool.tcp_addr),
            addr(&tool.zmq_sub_addr),
            addr(&tool.zmq_pub_addr),
        ));
    }
    code.push_str("];\n");
    fs::write(dest, code)?;
    Ok(())
}

#[derive(serde::Deserialize)]
struct ToolConfig {
    tool: Vec<ToolDefToml>,
}

#[derive(serde::Deserialize)]
struct ToolDefToml {
    name: String,
    hint: String,
    tcp_addr: Option<String>,
    zmq_sub_addr: Option<String>,
    zmq_pub_addr: Option<String>,
}
