use std::io::Result;
use std::{fs, path::Path};

fn main() -> Result<()> {
    // prost-build shells out to the system `protoc`.
    prost_build::Config::new()
        .compile_protos(&["proto/sim.proto"], &["proto"])?;
    println!("cargo:rerun-if-changed=proto/sim.proto");

    // Generate TASK_DEFS from tasks.toml.
    let tasks_toml = Path::new("tasks.toml");
    println!("cargo:rerun-if-changed={}", tasks_toml.display());

    let content = fs::read_to_string(tasks_toml)?;
    let config: TaskConfig = toml::from_str(&content)
        .expect("failed to parse tasks.toml");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("task_defs.rs");
    let mut code = String::from(
        "// Generated by build.rs from tasks.toml — do not edit.\n\
         pub const TASK_DEFS: &[TaskDef] = &[\n",
    );

    for task in &config.task {
        let cmds: Vec<String> = task.commands.iter().map(|c| format!("\"{c}\"")).collect();
        let cmds_str = if cmds.is_empty() {
            "&[]".to_string()
        } else {
            format!("&[{}]", cmds.join(", "))
        };
        code.push_str(&format!(
            "    TaskDef {{\n\
             \x20       name: \"{}\",\n\
             \x20       hint: \"{}\",\n\
             \x20       commands: {cmds_str},\n\
             \x20       border_color: ({}, {}, {}),\n\
             \x20   }},\n",
            task.name, task.hint,
            task.border_color[0], task.border_color[1], task.border_color[2],
        ));
    }
    code.push_str("];\n");
    fs::write(dest, code)?;
    Ok(())
}

#[derive(serde::Deserialize)]
struct TaskConfig {
    task: Vec<TaskDefToml>,
}

#[derive(serde::Deserialize)]
struct TaskDefToml {
    name: String,
    hint: String,
    #[serde(default)]
    commands: Vec<String>,
    #[serde(default)]
    border_color: Vec<u8>,
}
