/// Lightweight metadata for the tab bar.
#[derive(Debug, Clone)]
pub struct TaskInfo {
    pub name: String,
    /// Green dot in the tab bar when `true`.
    pub active: bool,
}

/// Static definition of a task tab.
#[derive(Debug, Clone)]
pub struct TaskDef {
    pub name: &'static str,
    pub hint: &'static str,
    #[allow(dead_code)]
    pub zmq_sub_addr: Option<&'static str>,
    #[allow(dead_code)]
    pub zmq_pub_addr: Option<&'static str>,
    pub tcp_addr: Option<&'static str>,
}

impl TaskDef {
    pub fn tcp_addr(&self) -> &str {
        self.tcp_addr.unwrap_or("127.0.0.1:7878")
    }

    #[allow(dead_code)]
    pub fn zmq_sub_addr(&self) -> &str {
        self.zmq_sub_addr.unwrap_or("tcp://127.0.0.1:5555")
    }

    #[allow(dead_code)]
    pub fn zmq_pub_addr(&self) -> &str {
        self.zmq_pub_addr.unwrap_or("tcp://127.0.0.1:5556")
    }
}

// Generated by build.rs — each entry maps to a [[task]] in tasks.toml.
include!(concat!(env!("OUT_DIR"), "/task_defs.rs"));
